#!/bin/bash
# Quick reference for building and releasing

echo "🍎 Argo Log Viewer - Build & Release Guide"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  ARM64 (Apple Silicon) Build - GitHub Actions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Go to: https://github.com/yourusername/argo-log-viewer/actions"
echo "   1. Click 'Build macOS Application'"
echo "   2. Click 'Run workflow'"
echo "   3. Enter version (e.g., 1.0.0)"
echo "   4. Select 'Create GitHub Release: true'"
echo "   5. Click 'Run workflow' button"
echo ""
echo "   ✅ This creates the release with ARM64 binaries (FREE)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  Intel (x86_64) Build - Local Intel Mac"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   On your Intel Mac, run:"
echo ""
echo "   ./build-intel-and-release.sh 1.0.0"
echo ""
echo "   Then manually upload DMG + ZIP through GitHub UI"
echo "   OR provide token for auto-upload:"
echo ""
echo "   ./build-intel-and-release.sh 1.0.0 ghp_yourtoken"
echo ""
echo "   ✅ This adds Intel binaries to the existing release"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Full Documentation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   See: BUILD-INTEL.md"
echo ""
